### ISSUE TITLE
Support BattleScribe 2.03

### ISSUE THREAD

**Issue by sprutton1** [WarHub/wham#46]
Specifically, the ability to add costs to an entry link. Unfortunately, files published by wham do not include this new feature.

![image](https://user-images.githubusercontent.com/3621657/65430814-82e87600-dde6-11e9-8800-784f40283c93.png)

**Comment by amis92** [comment]
@sprutton1 that is, indeed me not having updated wham to the new format, and also not checking for version compatibility yet.

Far more interesting to me though is, where is `wham` being actively used and how, I'm only aware of the AppVeyor stuff I set up for a few repos in bsdata.

**Comment by sprutton1** [comment]
I am creating/hosting files for OnePageRules' [Grimdark Future](https://onepagerules.com/portfolio/grimdark-future/). You can find them [here](https://github.com/sprutton1/GrimdarkFutureBattlescribe).

I stumbled across your project when trying to find a reasonable way to generate index files in CI.

**Comment by amis92** [comment]
For future reference, how Imports work:

* if a CatalogueLink specifies to Import Root Entries, all Root Entries marked as Import=true are imported into catalogue.
* if a CatalogueLink specifies ImportRootEntries=false, no Root Entries are imported no matter their Import status.

Ergo, Import is selecting what root entries *can* be imported, and ImportRootEntries specifies whether or not any entries *will* be imported.
